server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: faisal
    password: "@faisal17"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com # SMTP server for Gmail
    port: 587
    username: fm3233000@gmail.com
    password: cwjc cfxw nzzj pbsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
